### ISSUE TITLE
Needs ability to notify user if a marker is near a set of particular areas.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CaptainSpam/geohashdroid#34]
```
Once a day, this app should automatically check a list of points in a 
spreadsheet and see if it is anywhere near it.

e.g.
GPS point 1 , 1.0km , Home
GPS point 2 , 2.0km , Train station
GPS point 3 , 1.0km , Friends Place
GPS point 4 , 5.0km , Work
GPS point 5 , 3.0km , shopping
GPS point 6 , 0.5km , shopping 2
GPS point 7 , 4.0km , family ranch

If possible, users should be able to create these spreadsheet via a GUI 
interface in geohashdroid as well, by manually putting in points of interest 
and its trigger range.

You need to becareful to make this checks no more than once a day for battery 
life. Does android have cron jobs?
```

Original issue reported on code.google.com by `mofos...@gmail.com` on 16 Sep 2011 at 1:01

**Comment by mofosyne** [comment]
Hi, just wondering hows the app is going, and if there is any chance of implementing it in the near future.

Was thinking of chipping in a push or two etc, but read that you are overhauling the code. What's the current status?

**Comment by CaptainSpam** [comment]
The overhaul's coming along slowly, but definitely progressing.  I was getting stuck in a refactoring task I gave myself (if you forked it recently, you'll see a lot of mess around CentralMap and the new CentralMapMode-derived classes), but I think that's getting cleared up.

The first job in the overhaul is going to be getting all old functionality working (insofar as it fits the new interface), then I can get to adding fun tricks like this.  Or tracklogs.  I've wanted to have tracklog recording for a while now...

**Comment by CaptainSpam** [comment]
Finally got it!  Version 0.9.1 (now on Google Play or in the Releases section here) has a Known Locations feature which should do what you're expecting (so long as you turn on stock pre-fetching).  Check it out!

**Comment by mofosyne** [comment]
Cannot locate stock prefetching option in my phone. Is it possible for you
got 've a shortcut button to open the right settings? Other apps do that.
E.g. custom keyboards

**Comment by CaptainSpam** [comment]
The stock prefetch option should be in Preferences -> Other options, right on the top.  I can probably make that clearer in the reminder popup next time I update, sure.

**Comment by mofosyne** [comment]
Good idea, yea that sound be fine enough. Though a shortcut button would be
more convenient as well, in addition to instruction.
