### ISSUE TITLE
Start with last-used graticule or start in Select-A-Graticule mode

### ISSUE THREAD

**Issue by FriedrichFroebel** [CaptainSpam/geohashdroid#52]
Is there a way to save the last used graticule? I cannot even choose it by typing it in, I always have to move the map on app startup. Worked before the major app update.

**Comment by CaptainSpam** [comment]
Huh.  That's odd, most people I've ever heard from always wanted it to default to whatever's the closest hashpoint, not locked to a specific graticule.

As it stands right now, that's what it'll always default to, getting your current location, figuring out what the closest point is, and going with that.  But, I can make an option in preferences that tells it to remember the last-used graticule and skip the current location step, sure.

However, you said you can't even type it in?  As in, you go to the graticule mode (via the menu), you don't get a prompt to type in the graticule, and you can only tap it on the map?  If so, what device are you using?  That sounds like a bug I'm trying to hunt down that seems to be device-specific.

**Comment by FriedrichFroebel** [comment]
I tested several cases now and found a way to get the input dialog by turning the device from portrait mode to landscape mode and then turning it back to portrait mode. The overlay is visible in this case.
I am using a Samsung Galaxy SIII Mini.

**Comment by CaptainSpam** [comment]
I see.  That's quite odd.  I'll have to see if I can rethink how I put that box in there, then.  I've got an idea or two.

**Comment by CaptainSpam** [comment]
Okay, regarding the Graticule input box, I just pushed a change out to the Play Store which should fix that (version 0.9.0.3, which I will soon upload here as a release).  The part about starting with the most recently-used Graticule (or starting in Select-A-Graticule mode), that much I think I'll work on for the 0.9.1 release.

**Comment by CaptainSpam** [comment]
There we go.  Now appearing in the master branch (as per commit e2088857b9423ee343d01800f7aad8b486f44c73), there will be a new setting in preferences that will allow you to pick if you want to start with the closest hashpoint (the default, what it does now), the last-used graticule (or globalhash mode), or the graticule picker screen.  Once I've got the other parts of 0.9.1 finished, I'll get that out to the Play Store.

**Comment by CaptainSpam** [comment]
This feature is now in 0.9.1, which should be in the Google Play store now (or soon; it might take them a bit to get it through the system).  Enjoy!
