### ISSUE TITLE
Enhancement suggestion: Remember last used map type

### ISSUE THREAD

**Issue by jonasgraudums** [CaptainSpam/geohashdroid#56]
I find it a bit annoying that street map is always the default map type when invoking the app. Personally I prefer the satellite map since it gives a better hint of the location and whereabouts. Changing to it now is always three clicks away. I would like the app to remember my last recent map type selection.

**Comment by CaptainSpam** [comment]
Huh.  That's a good idea.  Not sure why I didn't add that in before.

I'll get it set that it'll just stash that away any time you switch the map type.  That should take care of it.

**Comment by CaptainSpam** [comment]
All right, that was pretty quick.  In commits 02defabf2fcd7d54ebabbc839fbc9c35672d113a and d8bd0368cd227107818d3b5017190b20699293f4 on the quickfixes branch, the app will now remember the last map type you used.  So that'll be in the next release, whenever I run one off.

Thanks!

**Comment by jonasgraudums** [comment]
Thanks. Please let me know if you need any help.

**Comment by CaptainSpam** [comment]
The 0.9.0.5 release is now out on GitHub, and I just posted it to the Play Store.  So, it should show up in a few hours there.  Enjoy!
