### ISSUE TITLE
Enhancement suggestion: Next day location

### ISSUE THREAD

**Issue by jonasgraudums** [CaptainSpam/geohashdroid#57]
I usually find myself checking GH location when it's too late and to check tomorrow I need to adjust date (4 clicks). I suggest a simple-to-reach-ui-element (maybe an extra dynamic option in the option menu?) that appears if there is a chance (UTC-wise) that the stock value for next day has been published. Clicking that would (if the coordinates are available) automatically increment current date and display location.

**Comment by CaptainSpam** [comment]
Hm... so, something like a "Try Tomorrow" option in the menu?  If there's nothing posted yet, that would just fail the way it normally would if you try to input a date that doesn't have anything yet, so that might be the easiest way to go about this.

**Comment by jonasgraudums** [comment]
I was thinking that the option should be disabled if the time is not due. Check current UTC and disable option if value not for grabs?

**Comment by jonasgraudums** [comment]
Yes. Why not have the "Try tomorrow"-option? Checking weekend hashes is a currently a pain.

**Comment by CaptainSpam** [comment]
Well, I've added the Try Tomorrow menu option in Geohash Droid as per commit 82f07652fbf3e71f1e57fad361a5ee8217a27a2a.  It'll show up if you're in expedition mode and actively on an expedition (if it doesn't have a valid Info yet, it won't show up).  I'll probably get that in 0.9.1 soon enough, but if you want to build it yourself, you can give it a go.

**Comment by CaptainSpam** [comment]
And we have liftoff.  It's in 0.9.1 now.  Enjoy!
