### ISSUE TITLE
Pre-dow open - West of W30

### ISSUE THREAD

**Issue by bflo-geohasher** [CaptainSpam/geohashdroid#59]
Looks like the droid app can't handle things before the Dow opens(I'm on the east coast, USA). If I open the app at 8:30 am, I obviously get the message that the stock price isn't out yet. However I still get that message and no pins if I change the date to yesterday, or further back. If I select a graticule E of W30(and yesterday's date), then I can select my graticule and select a previous date. 

Also had a question on known locations(awesome, btw), when would we get the notification? And if we have a location in the East, and we are West does that change the notification time, since they know the hash for the next day?

I'm pedalpusher on the wiki, btw(not sure I'll log in here much or remember my password in a few days).

**Comment by CaptainSpam** [comment]
The known location notifications are tied directly to the stock pre-fetcher (if you have pre-fetching turned off, you'll get a popup telling you this when you go to the editor).  That fires off at 9:30am every day, and is adjusted to make sure it's in Eastern Time as New York sees it, daylight saving time and all.  It's a half-hour past the official opening of the NYSE to account for any delays in getting the data out, of course.  So, around 9:30am ET should be when the notifications get sent out, if there's any to report.  Note that you'll need to start the app at least once whenever you power on your device; I don't have it set to react to bootup just yet, so the whole pre-fetcher wakeup alarm gets initialized when you enter the main map.

However, as for it not getting stock prices for ANY dates after it fails once?  Huh.  That's sort of weird.  I'll see about testing that out later tonight or tomorrow morning, but in the meantime, does it work after today's stock price IS available?  As in, if you leave the app and come back in, will it start working properly?

**Comment by bflo-geohasher** [comment]
Thanks for the timing update. 

Once today is available, it works as advertised. Going forward produces the "no price for that date" error, but the pin for today remains available.

As for the issue I'm seeing, The condition where it happens: Starting the app before 9:30am (before "today's" dow is published).
Then if I select an earlier date, I don't get pins for that date, just the "Today's dow has not been published yet" error.

To get around this, I can select a graticule east of W30, get the pins there, then select an earlier date(Leaving the date as "today" won't allow me to come back, because the dow still isn't published yet), and come back to my graticule. Then I can select any date, not including the date for "today". 

I always exited the app, and shut it down. Then restarting, produces the same conditions. 

I actually didn't test if just closing it and opening it would return to the initial conditions for the error(once I did the work-around), but I suspect it will. I can try tomorrow and let you know.

Also, I think you might have to wait until tomorrow to test since the app opens with the default of 'today' so you'll have valid data right now. Let me know if you want any screenshots.

**Comment by CaptainSpam** [comment]
Hm... that's troublesome.  I just tried it this morning.  I got the error that there was no stock value for today yet (on a non-30W graticule), but when I changed the date to yesterday, it worked and planted flags on the map appropriately.

I've got one more thing I can try tomorrow (namely, shutting off the stock cache), but I've got a feeling that I might need to make a build of the logging-specific version of GHD so I can get some logcat data from the app when it happens to you.

**Comment by bflo-geohasher** [comment]
Aha! I think I've narrowed the issue down some more, playing with it this morning. If I change the date to yesterday or earlier, then select the graticule, I'll get the "no stock price for today" error. If I first select the Graticule THEN change the date, it puts the pins down.

**Comment by CaptainSpam** [comment]
Wait a sec... you're saying you change the date to yesterday or earlier, THEN select the graticule?  By any chance, do you have it configured to go to the graticule picker on startup instead of the closest hashpoint or last-used graticule?

I ask this because I haven't been able to reproduce the issue on my phone, but I've had it set up to start with the closest hashpoint, which does things a bit differently.  If it's going to the graticule picker first, I might need to run different tests on Monday (obviously, the hashpoints for the weekend are already known, as the DJIA doesn't open again until Monday).

**Comment by bflo-geohasher** [comment]
I have it set to 'Start with the last-used graticule'. I hate using the Use Closest option because I'm up by the Great Lakes and if the hash in the western or northern grat is closest(I'm close to the NW corner so this happens a lot), the surrounding pins are kind of useless.

**Comment by CaptainSpam** [comment]
Still, Last-Used is a different option than what I've been using (I go with Use Closest, as I'm at the southern edge of a graticule in a very land-heavy region of the US, meaning the closest point might be just across the graticule edge), so I've got something else to check come Monday.  I'll see if I can get this reproduced then.

**Comment by CaptainSpam** [comment]
There we go.  Looks like that causes it; I was able to get it to not give me a stock price for yesterday when I tested it this morning.  From the looks of it, it's not even trying to grab a new stock price when the date gets changed, almost as if it doesn't think a graticule's been set yet.  I'll have to look into this a bit more, I've got an idea what might be doing it.

**Comment by CaptainSpam** [comment]
Got it.  As per commit 47a450125072a89e817b5097f6c31d60df58196c, when you use Last Used Graticule mode, it'll now do a better job of remembering what that graticule was if the stock lookup fails.  I'll get it pushed out to the Play Store soon.

Thanks for the bug report!

**Comment by bflo-geohasher** [comment]
Glad to help, thanks for the app and all the work you've done. It's pretty awesome.

**Comment by CaptainSpam** [comment]
The 0.9.1.2 release is out, and all appears to be well.  So, issue's being closed out.
