### ISSUE TITLE
Known Locations issue

### ISSUE THREAD

**Issue by bflo-geohasher** [CaptainSpam/geohashdroid#60]
It seems that there is an issue where selecting the 'only match with hashpoints in this graticule' option is not persistent. I have a known location in the corner of the SE graticule to my home graticule and only want to see hashes in that corner. When I select the above option, and close that window by selecting 'OK' and then going back into editing that location, the option is no longer selected. I found this today when I was notified of a close hash but it was in the adjacent graticule. 

Let me know if you need any more info.

Pedalpusher

**Comment by CaptainSpam** [comment]
Hm.  Yeah, that's a bit strange.  I'll look into that.

**Comment by CaptainSpam** [comment]
Oh, whoops.  Looks like when I added that feature, I forgot to add it to the serializer/deserializer, so it indeed never got saved along with the data (and thus never got considered when calculating nearby points).  I can get a fix for that pretty quickly, though you will need to manually set that back on any known locations you want it on.

**Comment by bflo-geohasher** [comment]
Cool, and thanks! I'll update my points after I see the update, or are reminded when a point is close, but not what I want.

**Comment by CaptainSpam** [comment]
I just pushed it out to the Play Store.  Hopefully in X amount of time it takes to propagate through the system, this should be fixed.  Thanks for the report!

**Comment by bflo-geohasher** [comment]
Saw the update and edited my known locations. Looks good now. Thanks for the fix!
