### ISSUE TITLE
Terrain/satellite map type options are switched

### ISSUE THREAD

**Issue by jonasgraudums** [CaptainSpam/geohashdroid#63]
In the map type menu the option for terrain shows satellite map and option for satellite shows terrain.

**Comment by CaptainSpam** [comment]
Oh.  Whoops.  I'll get that taken care of as soon as I can, then,

**Comment by CaptainSpam** [comment]
There we go.  The new version's been pushed out to the Play Store, and there's an APK waiting in the releases on GitHub.  Thanks for the report!
