### ISSUE TITLE
Problem fetching stock value

### ISSUE THREAD

**Issue by llavids** [CaptainSpam/geohashdroid#69]
The last three/four weeks there has been a problem with stock value fetching. Tried to uninstall/install the app again from Google Play but it didn't change the behavior.
Took a look at the code and there is DJIA data in both web sites found in code:

private final static String[] mServers = { "http://geo.crox.net/djia/%Y/%m/%d", "http://irc.peeron.com/xkcd/map/data/%Y/%m/%d"};

Unsure if there is a bug that prevents the app from getting the data.
Not a android developer, but can read the code. Picture added from app.
![Screenshot_20190822-103728_Geohash Droid](https://user-images.githubusercontent.com/54394956/63500004-4b299e00-c4c9-11e9-854f-95ae760add2b.jpg)

**Comment by CaptainSpam** [comment]
Hm, that's odd.  I'll have to check that out when I get home from work.  I wonder if something's gone weird with 30W graticules.

**Comment by CaptainSpam** [comment]
I can't seem to reproduce it on my end, but I'm trying to get a debug APK built up so you can get a logcat to send to me to see if that gives me any more clues.  Unfortunately, I'm chasing down a couple other bugs that are popping up while I'm doing that, so it might not be until tomorrow that I can get that up for download.

**Comment by llavids** [comment]
Great. I was thinking that since I've been using this app daily for some years, could be something that is cached (array overflowing)?

**Comment by CaptainSpam** [comment]
I don't think so.  While the app does cache hash data, it cleans the cache up as it goes along.  And, even if it weren't, that would've just kept adding more and more entries into a database on the device, so you might've noticed it taking up a ton of space if it got that bad. :-)

However, the fact that it's giving you that specific error means it checked for a stock value from at least one of the servers and got a 404 response.  There's a different error if there was any other problem talking to the servers.  Either way, that means it looked at the cache and didn't find anything.

But, I think I nailed down the bug I was seeing in the debug build.  I've attached an APK as a zipfile to this post.  You might need to look up how to install an APK to your device if you're not already familiar with it, but once you do, you should see another copy of the app in your launcher (the debug copy will have an icon of the stickfigure guy holding a red bug instead of a map).  This version has another option in the menu in the lower-right, "Dump Logcat Data".  That should get some logging data (ONLY from that version of Geohash Droid, not from anything else) and ask you how to share it.  You can save it to a file and paste it in here, or email it as a reply to this, or something.

Good luck!

[GeohashDroid-0.9.3-debug.zip](https://github.com/CaptainSpam/geohashdroid/files/3533338/GeohashDroid-0.9.3-debug.zip)

**Comment by llavids** [comment]
Got the dump log and read it myself. Could see that it used the correct URLs. Tried to surf to those (http://irc.peeron.com/xkcd/map/data/2019/08/22 and http://geo.crox.net/djia/2019/08/22) addresses on a Windows PC (network cable) - went ok. Tried the same on my Samsung - did not work. Got 404 from both. Tried just the host name (geo.crox.net) and got a response probably from my mesh network which could be the culprit. Disabled WiFi and the geohashing droid worked fine. Since I work from home, I guess most times I've tried using it from home which didn't work.
Tried using host name irc.peeron.com with WiFi (and mesh) from mobile and that worked fine on the other hand. So there is something with the web responses that conflicts with the mesh network (NetGear Orbi).

Log:

--------- beginning of main
08-23 10:00:37.560 14708 14708 I SELinux : SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=net.exclaimindustries.geohashdroid.debuggy 
08-23 10:00:37.564 14708 14708 I shdroid.debugg: Late-enabling -Xcheck:jni
08-23 10:00:37.751 14708 14708 D ConnectivityManager_URSP: Ursp sIsUrsp=false, sIsCheckUrsp=false, uid=10427
08-23 10:00:37.754 14708 14708 D Proxy   : urspP is null: 10427
08-23 10:00:37.759 14708 14708 I shdroid.debugg: The ClassLoaderContext is a special shared library.
08-23 10:00:37.764 14708 14708 I shdroid.debugg: The ClassLoaderContext is a special shared library.
08-23 10:00:38.111 14708 14726 D libEGL  : loaded /vendor/lib64/egl/libGLES_mali.so
08-23 10:00:38.184 14708 14708 D OpenGLRenderer: Skia GL Pipeline
08-23 10:00:38.217 14708 14708 I zzbz    : Making Creator dynamically
08-23 10:00:38.228 14708 14708 W shdroid.debugg: Unsupported class loader
08-23 10:00:38.233 14708 14708 W shdroid.debugg: Skipping duplicate class check due to unsupported classloader
08-23 10:00:38.236 14708 14708 I DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
08-23 10:00:38.236 14708 14708 I DynamiteModule: Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
08-23 10:00:38.266 14708 14708 W ChimeraDebugLogger: Singleton logger instance not set.
08-23 10:00:38.270 14708 14708 W shdroid.debugg: Unsupported class loader
08-23 10:00:38.277 14708 14708 W shdroid.debugg: Skipping duplicate class check due to unsupported classloader
08-23 10:00:38.331 14708 14708 I Google Maps Android API: Google Play services client version: 12451000
08-23 10:00:38.341 14708 14708 I Google Maps Android API: Google Play services package version: 18385039
08-23 10:00:38.722 14708 14708 W shdroid.debugg: Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
08-23 10:00:39.003 14708 14708 D CentralMap: We are version 924, we last reported version history on version 0
08-23 10:00:39.007 14708 14708 D CentralMap: Newest version with an entry is 925
08-23 10:00:39.103 14708 14708 D Dialog  : mIsSamsungBasicInteraction = false
08-23 10:00:39.103 14708 14708 D Dialog  : mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
08-23 10:00:39.143 14708 14708 D ScrollView: initGoToTop
08-23 10:00:39.170 14708 14708 D EmergencyMode: [EmergencyManager] android createPackageContext successful
08-23 10:00:39.188 14708 14708 D InputTransport: Input channel constructed: fd=92
08-23 10:00:39.189 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: setView = DecorView@cb1a073[CentralMap] TM=true MM=false
08-23 10:00:39.201 14708 14708 D InputTransport: Input channel constructed: fd=93
08-23 10:00:39.203 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: setView = DecorView@97bd0cf[CentralMap] TM=true MM=false
08-23 10:00:39.246 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: dispatchAttachedToWindow
08-23 10:00:39.437 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: Relayout returned: old=[0,72][1080,2076] new=[27,72][1053,2076] result=0x7 surface={valid=true 501985579008} changed=true
08-23 10:00:39.475 14708 14790 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-23 10:00:39.475 14708 14790 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-23 10:00:39.476 14708 14790 I OpenGLRenderer: Initialized EGL, version 1.4
08-23 10:00:39.476 14708 14790 D OpenGLRenderer: Swap behavior 2
08-23 10:00:39.492 14708 14790 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-23 10:00:39.493 14708 14790 D OpenGLRenderer: eglCreateWindowSurface = 0x74e0f41b80, 0x74e0ac1010
08-23 10:00:39.560 14708 14708 D AbsListView:  in onLayout changed 
08-23 10:00:39.573 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: dispatchAttachedToWindow
08-23 10:00:39.591 14708 14713 I shdroid.debugg: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
08-23 10:00:39.599 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: Relayout returned: old=[0,0][1080,2076] new=[0,0][1080,2076] result=0x7 surface={valid=true 501891211264} changed=true
08-23 10:00:39.615 14708 14790 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-23 10:00:39.615 14708 14790 D OpenGLRenderer: eglCreateWindowSurface = 0x74e0f41800, 0x74db0c2010
08-23 10:00:39.629 14708 14708 D ExpeditionMode: Here comes the empty start...
08-23 10:00:39.739 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: MSG_WINDOW_FOCUS_CHANGED 1 1
08-23 10:00:39.740 14708 14708 V InputMethodManager: Not IME target window, ignoring
08-23 10:00:39.964 14708 14785 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-23 10:00:39.979 14708 14765 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-23 10:00:39.983 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:39.983 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:39.989 14708 14765 D TcpOptimizer: TcpOptimizer-ON
08-23 10:00:40.012 14708 14790 I OpenGLRenderer: Davey! duration=757ms; Flags=0, IntendedVsync=245979568975918, Vsync=245980052309232, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=245980056746209, AnimationStart=245980056890171, PerformTraversalsStart=245980057891171, DrawStart=245980273370132, SyncQueued=245980282473786, SyncStart=245980283109325, IssueDrawCommandsStart=245980283757671, SwapBuffers=245980325020171, FrameCompleted=245980326674978, DequeueBufferDuration=4690000, QueueBufferDuration=372000, 
08-23 10:00:40.017 14708 14849 D AlarmService: Got STOCK_ALARM_OFF!
08-23 10:00:40.075 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: MSG_RESIZED_REPORT: frame=Rect(27, 72 - 1053, 2076) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
08-23 10:00:40.083 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2076) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
08-23 10:00:40.106 14708 14785 E BufferQueueProducer: [SurfaceTexture-0-14708-0] disconnect: not connected (req=1)
08-23 10:00:40.107 14708 14785 W libEGL  : EGLNativeWindowType 0x74f089e010 disconnect failed
08-23 10:00:40.107 14708 14785 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-23 10:00:40.185 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: MSG_WINDOW_FOCUS_CHANGED 0 1
08-23 10:00:40.946 14708 14786 W DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
08-23 10:00:40.958 14708 14786 I DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
08-23 10:00:40.958 14708 14786 I DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 4
08-23 10:00:40.964 14708 14786 W ChimeraDebugLogger: Singleton logger instance not set.
08-23 10:00:40.966 14708 14786 W shdroid.debugg: Unsupported class loader
08-23 10:00:40.972 14708 14786 W shdroid.debugg: Skipping duplicate class check due to unsupported classloader
08-23 10:00:41.131 14708 14766 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:41.131 14708 14766 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:42.009 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: MSG_WINDOW_FOCUS_CHANGED 1 1
08-23 10:00:42.010 14708 14708 V InputMethodManager: Not IME target window, ignoring
08-23 10:00:42.072 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: Relayout returned: old=[0,0][1080,2076] new=[0,0][1080,2076] result=0x1 surface={valid=true 501891211264} changed=false
08-23 10:00:43.225 14708 14767 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:43.225 14708 14767 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:43.625 14708 14898 V HashBuilder: Checking caches for 20190823 with 30W rule
08-23 10:00:43.625 14708 14898 V HashBuilder: Checking quickcache for data...
08-23 10:00:43.625 14708 14898 V HashBuilder: Data wasn't in quickcache.
08-23 10:00:43.665 14708 14898 V StockStoreDatabase: Querying the hashes database...
08-23 10:00:43.667 14708 14898 V StockStoreDatabase: Info doesn't exist in database
08-23 10:00:43.671 14708 14898 D StockRunner: Now starting a StockRunner for 2019-08-23 at 55N 13E...
08-23 10:00:43.672 14708 14898 V HashBuilder: Checking caches for 20190823 with 30W rule
08-23 10:00:43.672 14708 14898 V HashBuilder: Checking quickcache for data...
08-23 10:00:43.672 14708 14898 V HashBuilder: Data wasn't in quickcache.
08-23 10:00:43.672 14708 14898 V StockStoreDatabase: Querying the hashes database...
08-23 10:00:43.673 14708 14898 V StockStoreDatabase: Info doesn't exist in database
08-23 10:00:43.674 14708 14898 V HashBuilder: Going to the database for a stock for 20190822
08-23 10:00:43.674 14708 14898 V StockStoreDatabase: Querying the stock database...
08-23 10:00:43.675 14708 14898 V StockStoreDatabase: Stock doesn't exist in database
08-23 10:00:43.676 14708 14898 V StockRunner: Trying http://irc.peeron.com/xkcd/map/data/2019/08/22...
08-23 10:00:43.937 14708 14898 D StockRunner: Server said there was no stock for 2019-08-22
08-23 10:00:43.937 14708 14898 V StockRunner: Trying http://geo.crox.net/djia/2019/08/22...
08-23 10:00:44.071 14708 14898 D StockRunner: Server said there was no stock for 2019-08-22
08-23 10:00:44.071 14708 14898 D StockService: Stock isn't posted yet.
08-23 10:00:44.072 14708 14898 D StockService: Dispatching intent...
08-23 10:00:44.076 14708 14713 I shdroid.debugg: Compiler allocated 4MB to compile void android.view.ViewRootImpl.performTraversals()
08-23 10:00:44.078 14708 14708 D StockReceiver: Stock has come in!
08-23 10:00:44.655 14708 14768 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:44.656 14708 14768 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.669 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.670 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.700 14708 14766 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.700 14708 14766 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.702 14708 14767 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.702 14708 14767 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.716 14708 14768 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.716 14708 14768 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.777 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.777 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:45.871 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:00:46.115 14708 14765 I chatty  : uid=10427(net.exclaimindustries.geohashdroid.debuggy) Thread-6 identical 2 lines
08-23 10:00:46.115 14708 14765 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-23 10:01:00.268 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: ViewPostIme pointer 0
08-23 10:01:00.317 14708 14708 D AbsListView: reportScrollStateChange() newState : 1
08-23 10:01:00.930 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: ViewPostIme pointer 1
08-23 10:01:00.930 14708 14708 D AbsListView: onTouchUp() mTouchMode : 3
08-23 10:01:00.931 14708 14708 D AbsListView: onTouchUp() TOUCH_MODE_SCROLL initialVelocity : -700
08-23 10:01:00.931 14708 14708 D AbsListView: reportScrollStateChange() newState : 2
08-23 10:01:01.584 14708 14708 D AbsListView: reportScrollStateChange() newState : 0
08-23 10:01:04.972 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: ViewPostIme pointer 0
08-23 10:01:05.043 14708 14708 D AbsListView: reportScrollStateChange() newState : 1
08-23 10:01:05.459 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: ViewPostIme pointer 1
08-23 10:01:05.460 14708 14708 D AbsListView: onTouchUp() mTouchMode : 3
08-23 10:01:05.460 14708 14708 D AbsListView: onTouchUp() TOUCH_MODE_SCROLL initialVelocity : -1234
08-23 10:01:05.460 14708 14708 D AbsListView: reportScrollStateChange() newState : 2
08-23 10:01:06.361 14708 14708 D AbsListView: reportScrollStateChange() newState : 0
08-23 10:01:08.581 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: ViewPostIme pointer 0
08-23 10:01:08.651 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: ViewPostIme pointer 1
08-23 10:01:08.678 14708 14790 W libEGL  : EGLNativeWindowType 0x74e0ac1010 disconnect failed
08-23 10:01:08.678 14708 14790 D OpenGLRenderer: eglDestroySurface = 0x74e0f41b80, 0x74e0ac1000
08-23 10:01:08.679 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: dispatchDetachedFromWindow
08-23 10:01:08.680 14708 14708 D ViewRootImpl@9f084e2[CentralMap]: Surface release. android.view.ViewRootImpl.doDie:7954 android.view.ViewRootImpl.die:7922 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.Dialog.dismissDialog:518 android.app.Dialog.dismiss:501 android.app.DialogFragment.dismissInternal:295 
08-23 10:01:08.712 14708 14708 D InputTransport: Input channel destroyed: fd=92
08-23 10:01:08.718 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: MSG_WINDOW_FOCUS_CHANGED 1 1
08-23 10:01:08.722 14708 14708 D InputMethodManager: prepareNavigationBarInfo() DecorView@97bd0cf[CentralMap]
08-23 10:01:08.722 14708 14708 D InputMethodManager: getNavigationBarColor() -855310
08-23 10:01:08.728 14708 14708 D InputMethodManager: prepareNavigationBarInfo() DecorView@97bd0cf[CentralMap]
08-23 10:01:08.729 14708 14708 D InputMethodManager: getNavigationBarColor() -855310
08-23 10:01:08.729 14708 14708 V InputMethodManager: Starting input: tba=net.exclaimindustries.geohashdroid.debuggy ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
08-23 10:01:08.729 14708 14708 D InputMethodManager: startInputInner - Id : 0
08-23 10:01:08.729 14708 14708 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
08-23 10:01:08.735 14708 14708 E ViewRootImpl: sendUserActionEvent() returned.
08-23 10:01:08.746 14708 14732 D InputTransport: Input channel constructed: fd=92
08-23 10:01:08.747 14708 14708 D InputMethodManager: prepareNavigationBarInfo() DecorView@97bd0cf[CentralMap]
08-23 10:01:08.747 14708 14708 D InputMethodManager: getNavigationBarColor() -855310
08-23 10:01:08.747 14708 14708 V InputMethodManager: Starting input: tba=net.exclaimindustries.geohashdroid.debuggy ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
08-23 10:01:08.747 14708 14708 D InputMethodManager: startInputInner - Id : 0
08-23 10:01:10.428 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: ViewPostIme pointer 0
08-23 10:01:10.518 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: ViewPostIme pointer 1
08-23 10:01:10.681 14708 14708 D InputTransport: Input channel constructed: fd=122
08-23 10:01:10.684 14708 14708 D ViewRootImpl@c6e2d74[PopupWindow:7379161]: setView = android.widget.PopupWindow$PopupDecorView{87ae29d V.E...... R.....I. 0,0-0,0} TM=true MM=false
08-23 10:01:10.690 14708 14713 I shdroid.debugg: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
08-23 10:01:10.707 14708 14708 V InputMethodManager: Not IME target window, ignoring
08-23 10:01:10.709 14708 14708 D ViewRootImpl@c6e2d74[PopupWindow:7379161]: dispatchAttachedToWindow
08-23 10:01:10.730 14708 14708 D ViewRootImpl@c6e2d74[PopupWindow:7379161]: Relayout returned: old=[0,72][1080,2076] new=[372,986][1080,1908] result=0x7 surface={valid=true 501858172928} changed=true
08-23 10:01:10.738 14708 14790 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-23 10:01:10.739 14708 14790 D OpenGLRenderer: eglCreateWindowSurface = 0x74d951b500, 0x74d9140010
08-23 10:01:10.812 14708 14708 D AbsListView:  in onLayout changed 
08-23 10:01:10.814 14708 14708 D ViewRootImpl@c6e2d74[PopupWindow:7379161]: MSG_WINDOW_FOCUS_CHANGED 1 1
08-23 10:01:10.815 14708 14708 V InputMethodManager: Not IME target window, ignoring
08-23 10:01:10.923 14708 14708 D ViewRootImpl@c6e2d74[PopupWindow:7379161]: MSG_RESIZED: frame=Rect(372, 986 - 1080, 1908) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
08-23 10:01:10.971 14708 14708 D ViewRootImpl@a960d2e[CentralMap]: MSG_WINDOW_FOCUS_CHANGED 0 1
08-23 10:01:10.972 14708 14708 D InputMethodManager: prepareNavigationBarInfo() DecorView@97bd0cf[CentralMap]
08-23 10:01:10.972 14708 14708 D InputMethodManager: getNavigationBarColor() -855310
--------- beginning of system
08-23 10:01:10.973 14708 14708 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
08-23 10:01:12.291 14708 14708 D ViewRootImpl@c6e2d74[PopupWindow:7379161]: ViewPostIme pointer 0
08-23 10:01:12.305 14708 14708 D ViewRootImpl@c6e2d74[PopupWindow:7379161]: ViewPostIme pointer 1
08-23 10:01:12.307 14708 14708 D AbsListView: onTouchUp() mTouchMode : 0

**Comment by llavids** [comment]
Seems that I have a double NAT issue in my network, which could explain some other problems I've experienced time to time. Have to reconfigure home network. At least I now know what to do to get the geohashe :)

**Comment by llavids** [comment]
I disabled WiFi in ISP router and changed my Orbi Mesh to act as AP and now geohashdroid worked fine. Tested host geo.crox.net with and without date and it worked fine. Case closed then. Thanks!

**Comment by CaptainSpam** [comment]
Awesome, then!  Thanks!
