### ISSUE TITLE
Photo Upload to Wiki is broken

### ISSUE THREAD

**Issue by nineff** [CaptainSpam/geohashdroid#77]
Version: 0.9.5 (btw: the release date in the app still says 2020 instead of 2021...)
OS: Android 11 

When you chose to upload an image to the wiki with this version, the image does not show up on the Wiki page. Instead, only it's caption and coordinates which link to OSM are inserted like a regular Wiki-Message. The setting "draw infobox" also apparently has no effect, the result is always the same.

I don't know if the pictures actually get uploaded and are just not correctly inserted on the wiki or if they don't get used at all.

**Comment by CaptainSpam** [comment]
Hm.  Okay, I think I see what's going on.  Well, part of it.  I'm not serializing the internal image URI correctly.  That much I can fix easily.

But, it looks like newer Android versions also throw a permission error when I try that now.  I'll get on this.

**Comment by CaptainSpam** [comment]
Got it.  Looks like there was a permissions thing I wasn't accounting for that stopped the uploading service from doing anything with images.  I've got that resolved now, and I'll get a new release up in a few minutes (plus the Play Store's review time).

**Comment by CaptainSpam** [comment]
Version 0.9.5.1 is now live on the GitHub site.  It's also been submitted to the Play Store, so it'll show up there at some point in the near future, I'd assume.  Hopefully this fixes things!

**Comment by nineff** [comment]
Awesome, this was really fast! I guess I have to go hashing now to test it
