### ISSUE TITLE
Can't open the preferences (black screen) 

### ISSUE THREAD

**Issue by guillaumebrunerie** [CaptainSpam/geohashdroid#79]
When I try to open the preferences, it only shows a black screen (see screenshot), so I cannot access the preferences at all anymore. It is somewhat recent, it used to work, so I guess one of the latest updates? I'm not sure how to get a log or an error message or something like that. Let me know if I can do something to help debug it. 

Thanks! 

![Screenshot_20210801-222739](https://user-images.githubusercontent.com/787865/127784503-84aeca08-d6a4-473a-814e-f6e4c77495f7.png)

**Comment by guillaumebrunerie** [comment]
Actually, it looks like the menu is there but black on black. Clicking around does stuff, for instance:

![Screenshot_20210801-223526](https://user-images.githubusercontent.com/787865/127784659-292c8167-7f85-453a-b0bf-c6ae0338971c.png)

But the main menu is really absolutely black on black :D

**Comment by CaptainSpam** [comment]
Ah, dangit.  I was a little afraid the theme style I was using might cause problems at some point, and, well, I guess it does now.

As far as I know, what I'm doing SHOULD give the right text colors there, but unfortunately, I've seen something similar happen in some of the developer emulators, too.  I've had plans to redo everything to fit more modern versions of Android (especially with respects to dark/night themes), which should fix this.  Looks like I might need to step that up a bit, then.

I'll see what I can do with that.  It might be a somewhat major update that fixes this along with a bunch of other stuff.

Thanks for the report!

**Comment by guillaumebrunerie** [comment]
Indeed, it works if I disable dark mode (but then it's not in dark mode, of course :) ).

**Comment by CaptainSpam** [comment]
Hey, sorry it took so long to get the release out, but the latest version, 0.9.6, should now use a more proper night mode (and the more modern preference classes), so hopefully that'll fix the font color issues in the preferences screens.  If you're still checking, could you give it a shot?

**Comment by guillaumebrunerie** [comment]
It does work now, thanks!
