### ISSUE TITLE
Different notification radiuses for graticules and globalhash

### ISSUE THREAD

**Issue by quassnoi** [CaptainSpam/geohashdroid#85]
Can we please have an option to set up a larger notification radius for the globalhash?

If globalhash happens to fall within a 100 mile radius from my location I'm happy to drive or take a train or whatever takes me there, but of course I'm not doing it for the run-of-the-mill graticule spots.

Thank you!

**Comment by CaptainSpam** [comment]
Hmm... I can see that making sense, yeah.  I'll see what I can do with it once I find some time, that should be relatively simple to add in.

**Comment by CaptainSpam** [comment]
There we go!  I've added it in to 0.9.6.1.  An APK is here on Github now, and will appear on the Play Store in an amount of time.  Thanks!

**Comment by quassnoi** [comment]
Noaice!!!

One small thing... can we please have something like 50 km, 100 km and 200 km for globalhashes? Right now it's capped at 20km, the same as graticules, and that's what I actually have set up anyway.

Thanks!

**Comment by CaptainSpam** [comment]
Sure, I can add those in.  Though that'll probably be tomorrow or so.

**Comment by CaptainSpam** [comment]
And there!  Version 0.9.6.2 has gone out to both Github and the Play Store.  The ranges for both normal hashes and globalhashes now go up to 200km.  Enjoy!
